### ISSUE TITLE
gs-pypi-generate-db: ERROR 404: Not Found.

### ISSUE THREAD

**Issue by l29ah** [jauhien/gs-pypi#16]
```
‰ gs-pypi-generate-db .g-sorcery/gs_pypi/pypi/db/
--2018-04-24 23:38:00--  https://pypi.python.org/pypi?%3Aaction=index
Resolving pypi.python.org (pypi.python.org)... 151.101.84.223, 2a04:4e42:14::223
Connecting to pypi.python.org (pypi.python.org)|151.101.84.223|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi?%3Aaction=index [following]
--2018-04-24 23:38:00--  https://pypi.org/pypi?%3Aaction=index
Resolving pypi.org (pypi.org)... 151.101.64.223, 151.101.0.223, 151.101.128.223, ...
Connecting to pypi.org (pypi.org)|151.101.64.223|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/?%3Aaction=index [following]
--2018-04-24 23:38:01--  https://pypi.org/pypi/?%3Aaction=index
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 404 Not Found
2018-04-24 23:38:01 ERROR 404: Not Found.

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/gs-pypi-generate-db", line 18, in <module>
    sys.exit(gs_pypi_generate_db.main())
  File "/usr/lib64/python3.5/site-packages/gs_pypi/gs_pypi_generate_db.py", line 68, in main
    common_config=config["common_config"])
  File "/usr/lib64/python3.5/site-packages/g_sorcery/package_db.py", line 563, in __call__
    self.generate_tree(pkg_db, common_config, config)
  File "/usr/lib64/python3.5/site-packages/g_sorcery/package_db.py", line 577, in generate_tree
    data = self.download_data(common_config, config)
  File "/usr/lib64/python3.5/site-packages/g_sorcery/package_db.py", line 595, in download_data
    self.process_uri(uri, data)
  File "/usr/lib64/python3.5/site-packages/g_sorcery/package_db.py", line 606, in process_uri
    data.update(load_remote_file(**uri))
  File "/usr/lib64/python3.5/site-packages/g_sorcery/fileutils.py", line 283, in load_remote_file
    raise DownloadingError("wget failed: " + uri)
g_sorcery.exceptions.DownloadingError: wget failed: https://pypi.python.org/pypi?%3Aaction=index
```

**Comment by brainwane** [comment]
Might be related to https://warehouse.readthedocs.io/api-reference/integration-guide/#migrating-to-the-new-pypi and https://blog.python.org/2018/04/new-pypi-launched-legacy-pypi-shutting.html .
