### ISSUE TITLE
Failed to add repo to layman with pyvisa

### ISSUE THREAD

**Issue by Faraclas** [jauhien/gs-pypi#2]
Ok, I am trying to use this method now and getting some errors. I have installed gs-pypi and edited

/etc/g-sorcery/g-sorcery.cfg

```
[main]
package_manager=portage
[gs-pypi]
pypi_packages=pyvisa
```

Then

```
eliasgentoo elias # layman -L | grep pypi
 * pypi                      [g-sorcery ] (gs-pypi pypi                        )    
```

Then (the error)

```
eliasgentoo elias # layman -a pypi

 * Adding overlay...
 * Overlay "pypi" is not an official. Continue install? [y/n]: y
 * Running ... # ( cd /var/lib/layman/pypi  && /usr/bin/g-sorcery gs-pypi -o /var/lib/layman/pypi -r pypi sync )
--2015-07-01 10:12:40--  https://github.com/jauhien/gs-pypi-db/archive/bson.tar.gz
Resolving github.com... 192.30.252.130
Connecting to github.com|192.30.252.130|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/jauhien/gs-pypi-db/tar.gz/bson [following]
--2015-07-01 10:12:40--  https://codeload.github.com/jauhien/gs-pypi-db/tar.gz/bson
Resolving codeload.github.com... 192.30.252.147
Connecting to codeload.github.com|192.30.252.147|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/tmp/tmprdHXS1/bson.tar.gz’

/tmp/tmprdHXS1/bson     [    <=>               ]   6.04M  9.13MB/s   in 0.7s   

2015-07-01 10:12:42 (9.13 MB/s) - ‘/tmp/tmprdHXS1/bson.tar.gz’ saved [6331065]

 * unpacking /tmp/tmprdHXS1/bson.tar.gz
gs-pypi-db-bson/
gs-pypi-db-bson/categories.json
gs-pypi-db-bson/dev-python/
gs-pypi-db-bson/dev-python/packages.bson
gs-pypi-db-bson/manifest.json
gs-pypi-db-bson/metadata.json
 * copy files to an actual database
‘/tmp/tmpMEz4me/gs-pypi-db-bson/categories.json’ -> ‘/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/categories.json’
‘/tmp/tmpMEz4me/gs-pypi-db-bson/dev-python’ -> ‘/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/dev-python’
‘/tmp/tmpMEz4me/gs-pypi-db-bson/dev-python/packages.bson’ -> ‘/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/dev-python/packages.bson’
‘/tmp/tmpMEz4me/gs-pypi-db-bson/manifest.json’ -> ‘/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/manifest.json’
‘/tmp/tmpMEz4me/gs-pypi-db-bson/metadata.json’ -> ‘/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/metadata.json’
 * Running g-sorcery... # ( cd /var/lib/layman/pypi  && /usr/bin/g-sorcery gs-pypi -o /var/lib/layman/pypi generate-tree )
 * tree generation
 * no package with name pyvisa found

Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/g-sorcery", line 18, in <module>
    sys.exit(g_sorcery.main())
  File "/usr/lib64/python2.7/site-packages/g_sorcery/g_sorcery.py", line 68, in main
    return backend.instance(sys.argv[2:], config, global_config)
  File "/usr/lib64/python2.7/site-packages/g_sorcery/backend.py", line 641, in __call__
    return args.func(args, config, global_config)
  File "/usr/lib64/python2.7/site-packages/g_sorcery/backend.py", line 526, in generate_tree
    dependencies |= self.get_dependencies(pkg_db, pkg)
  File "/usr/lib64/python2.7/site-packages/g_sorcery/backend.py", line 347, in get_dependencies
    raise DependencyError(error)
g_sorcery.exceptions.DependencyError: no package with name pyvisa found
 * Failure result returned from g-sorcery
 * Adding repository "pypi" failed! Possible remains of the operation have NOT been removed and may be left at "/var/lib/layman/pypi". Please remove them manually if required.

 * CLI: Errors occurred processing action add
 * Adding repository "pypi" failed! Possible remains of the operation have NOT been removed and may be left at "/var/lib/layman/pypi". Please remove them manually if required.
```

**Comment by jauhien** [comment]
I'm not on my machine now, but I guess the package is called PyVISA (https://pypi.python.org/pypi/PyVISA), please, try with this name. `gs-pypi` does not change name of the package if it is valid.

**Comment by Faraclas** [comment]
Thank you.  I made the change and now get the following error:

```
eliasgentoo elias # layman -a pypi

 * Adding overlay...
 * Overlay "pypi" is not an official. Continue install? [y/n]: y
 * Running ... # ( cd /var/lib/layman/pypi  && /usr/bin/g-sorcery gs-pypi -o /var/lib/layman/pypi -r pypi sync )
--2015-07-06 09:57:44--  https://github.com/jauhien/gs-pypi-db/archive/bson.tar.gz
Resolving github.com... 192.30.252.129
Connecting to github.com|192.30.252.129|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/jauhien/gs-pypi-db/tar.gz/bson [following]
--2015-07-06 09:57:44--  https://codeload.github.com/jauhien/gs-pypi-db/tar.gz/bson
Resolving codeload.github.com... 192.30.252.144
Connecting to codeload.github.com|192.30.252.144|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/tmp/tmprt0o900a/bson.tar.gz’

/tmp/tmprt0o900a/bson.tar.gz                     [   <=>                                                                                         ]   6.19M  9.54MB/s   in 0.6s   

2015-07-06 09:57:46 (9.54 MB/s) - ‘/tmp/tmprt0o900a/bson.tar.gz’ saved [6495312]

 * unpacking /tmp/tmprt0o900a/bson.tar.gz
gs-pypi-db-bson/
gs-pypi-db-bson/categories.json
gs-pypi-db-bson/dev-python/
gs-pypi-db-bson/dev-python/packages.bson
gs-pypi-db-bson/manifest.json
gs-pypi-db-bson/metadata.json
 * copy files to an actual database
‘/tmp/tmpy49mkifi/gs-pypi-db-bson/categories.json’ -> ‘/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/categories.json’
‘/tmp/tmpy49mkifi/gs-pypi-db-bson/dev-python’ -> ‘/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/dev-python’
‘/tmp/tmpy49mkifi/gs-pypi-db-bson/dev-python/packages.bson’ -> ‘/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/dev-python/packages.bson’
‘/tmp/tmpy49mkifi/gs-pypi-db-bson/manifest.json’ -> ‘/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/manifest.json’
‘/tmp/tmpy49mkifi/gs-pypi-db-bson/metadata.json’ -> ‘/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/metadata.json’
 * Running g-sorcery... # ( cd /var/lib/layman/pypi  && /usr/bin/g-sorcery gs-pypi -o /var/lib/layman/pypi generate-tree )
 * tree generation
 *     generating dev-python/PyVISA-1.7
 * fast digesting overlay
 * ReposConf: ConfigHandler.read(); Failed to read "/etc/portage/repos.conf/layman.conf".
 * File not found.

 * CLI: Errors occurred processing action add
 * ReposConf: ConfigHandler.read(); Failed to read "/etc/portage/repos.conf/layman.conf".
 * File not found.
 * Exception caught installing repository 'pypi' : ConfigHandler instance has no attribute 'repo_conf'
```

Then trying to use the PyVISA ebuild also fails

```
eliasgentoo elias # emerge -av dev-python/PyVISA

These are the packages that would be merged, in order:

Calculating dependencies... done!

emerge: there are no ebuilds to satisfy "dev-python/PyVISA".

emerge: searching for similar names...
emerge: Maybe you meant any of these: dev-python/pyvorbis, dev-python/pyinsane, dev-python/visual?
```

**Comment by jauhien** [comment]
Please, try to read output that you have before opening an issue. Also, please, read documentation (https://wiki.gentoo.org/wiki/Layman#Configuration). You probably have some problems with layman configuration. What was you trying to achieve running `emerge -av dev-python/PyVISA` is beyond my understanding.

If after reading docs and doing proper configuration you'll have real problem, feel free to open new issue.

You can always ask for help on IRC (#gentoo on freenode) or forums (https://forums.gentoo.org/).

**Comment by jauhien** [comment]
To be finally sure, that the problem is not in gs-pypi, please, try to execute `sudo layman -a science` or any other repo. If it does not fall, please, feel free to reopen this issue.

**Comment by Faraclas** [comment]
Thank you. Including g-sorcery forced layman to be updated.  

```
layman-updater -R
```

fixed the issue.
