### ISSUE TITLE
DependencyError: no package with name keras found

### ISSUE THREAD

**Issue by dniku** [jauhien/gs-pypi#6]
`keras` is definitely in PyPI:

```
$ pip install keras
Collecting keras
  Downloading Keras-0.3.1.tar.gz (69kB)
  ...
```

However, attempting to register it in `/etc/g-sorcery/g-sorcery.cfg` and install it fails with `DependencyError`:

```
$ sudo layman -s pypi

 * Fetching remote list...
 * Fetch Ok

 * Syncing selected overlay(s)...
 * Running ... # ( cd /var/lib/layman/pypi  && /usr/bin/g-sorcery gs-pypi -o /var/lib/layman/pypi -r pypi sync )
Already up-to-date.
 * copy files to an actual database
«/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/categories.json» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/categories.json»
«/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/dev-python» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/dev-python»
«/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/dev-python/packages.bson» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/dev-python/packages.bson»
«/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/manifest.json» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/manifest.json»
«/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/metadata.json» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/metadata.json»
 * Running g-sorcery... # ( cd /var/lib/layman/pypi  && /usr/bin/g-sorcery gs-pypi -o /var/lib/layman/pypi generate-tree )
 * tree generation
!!! Repository 'pypi' is missing masters attribute in '/var/lib/layman/pypi/metadata/layout.conf'
!!! Set 'masters = gentoo' in this file for future compatibility
 * no package with name keras found

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/g-sorcery", line 18, in <module>
    sys.exit(g_sorcery.main())
  File "/usr/lib64/python3.4/site-packages/g_sorcery/g_sorcery.py", line 68, in main
    return backend.instance(sys.argv[2:], config, global_config)
  File "/usr/lib64/python3.4/site-packages/g_sorcery/backend.py", line 652, in __call__
    return args.func(args, config, global_config)
  File "/usr/lib64/python3.4/site-packages/g_sorcery/backend.py", line 530, in generate_tree
    dependencies |= self.get_dependencies(pkg_db, pkg)
  File "/usr/lib64/python3.4/site-packages/g_sorcery/backend.py", line 351, in get_dependencies
    raise DependencyError(error)
g_sorcery.exceptions.DependencyError: no package with name keras found
 * Failure result returned from g-sorcery
 * 
 * Errors:
 * ------
 * Failed to sync overlay "pypi".
 * Error was: Syncing overlay "pypi" returned status 1!
 * db.sync()
 * 

 * CLI: Errors occurred processing action sync
 * 
 * Errors:
 * ------
 * Failed to sync overlay "pypi".
 * Error was: Syncing overlay "pypi" returned status 1!
 * db.sync()
 *
```

**Comment by jauhien** [comment]
You have `Keras` in pypi, not `keras` I guess.

**Comment by jauhien** [comment]
Yes, I'm right, package name is `dev-python/Keras-0.3.1`.

**Comment by dniku** [comment]
Whoops! Sorry for disturbing.

Although since `pip` resolves it, maybe `gs-pypi` should too.
