### ISSUE TITLE
no package with name skflow found

### ISSUE THREAD

**Issue by dniku** [jauhien/gs-pypi#7]
(this time it's not Skflow or something like that)

```
$ sudo layman -s pypi

 * Fetching remote list...
 * Fetch Ok

 * Syncing selected overlay(s)...
 * Running ... # ( cd /var/lib/layman/pypi  && /usr/bin/g-sorcery gs-pypi -o /var/lib/layman/pypi -r pypi sync )
Already up-to-date.
 * copy files to an actual database
«/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/categories.json» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/categories.json»
«/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/dev-python» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/dev-python»
«/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/dev-python/packages.bson» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/dev-python/packages.bson»
«/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/manifest.json» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/manifest.json»
«/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/metadata.json» -> «/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/metadata.json»
 * Running g-sorcery... # ( cd /var/lib/layman/pypi  && /usr/bin/g-sorcery gs-pypi -o /var/lib/layman/pypi generate-tree )
 * tree generation
!!! Repository 'pypi' is missing masters attribute in '/var/lib/layman/pypi/metadata/layout.conf'
!!! Set 'masters = gentoo' in this file for future compatibility
 * no package with name skflow found

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/g-sorcery", line 18, in <module>
    sys.exit(g_sorcery.main())
  File "/usr/lib64/python3.4/site-packages/g_sorcery/g_sorcery.py", line 68, in main
    return backend.instance(sys.argv[2:], config, global_config)
  File "/usr/lib64/python3.4/site-packages/g_sorcery/backend.py", line 652, in __call__
    return args.func(args, config, global_config)
  File "/usr/lib64/python3.4/site-packages/g_sorcery/backend.py", line 530, in generate_tree
    dependencies |= self.get_dependencies(pkg_db, pkg)
  File "/usr/lib64/python3.4/site-packages/g_sorcery/backend.py", line 351, in get_dependencies
    raise DependencyError(error)
g_sorcery.exceptions.DependencyError: no package with name skflow found
 * Failure result returned from g-sorcery
 * 
 * Errors:
 * ------
 * Failed to sync overlay "pypi".
 * Error was: Syncing overlay "pypi" returned status 1!
 * db.sync()
 * 

 * CLI: Errors occurred processing action sync
 * 
 * Errors:
 * ------
 * Failed to sync overlay "pypi".
 * Error was: Syncing overlay "pypi" returned status 1!
 * db.sync()
 * 

$ pip install --user skflow
Collecting skflow
  Downloading skflow-0.1.0.tar.gz
Collecting sklearn (from skflow)
  Downloading sklearn-0.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): scipy in /usr/lib64/python3.4/site-packages (from skflow)
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib64/python3.4/site-packages (from skflow)
Requirement already satisfied (use --upgrade to upgrade): scikit-learn in /usr/lib64/python3.4/site-packages (from sklearn->skflow)
Building wheels for collected packages: skflow, sklearn
  Running setup.py bdist_wheel for skflow
  Stored in directory: /home/pastafarianist/.cache/pip/wheels/fe/1b/2c/25df8955c97d579fd768b3229088ee689e6c8c2b5d8103e155
  Running setup.py bdist_wheel for sklearn
  Stored in directory: /home/pastafarianist/.cache/pip/wheels/df/0e/0e/8f29513562deeafd8e895b4e60df6b05be4e937810d420f141
Successfully built skflow sklearn
Installing collected packages: sklearn, skflow
Successfully installed skflow-0.1.0 sklearn-0.0
```

**Comment by sjlongland** [comment]
Seeing the same problem with `pint`:

```
vk4msl-ws ~ # layman -a pypi

 * Adding overlay...
 * Overlay "pypi" is not official. Continue installing? [y/n]: y
 * Running ... # ( cd /var/lib/layman/pypi  && /usr/bin/g-sorcery gs-pypi -o /var/lib/layman/pypi -r pypi sync )
Cloning into '/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
 * copy files to an actual database
'/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/categories.json' -> '/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/categories.json'
'/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/dev-python' -> '/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/dev-python'
'/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/dev-python/packages.bson' -> '/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/dev-python/packages.bson'
'/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/manifest.json' -> '/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/manifest.json'
'/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/persistent/remote/metadata.json' -> '/var/lib/layman/pypi/.g-sorcery/gs_pypi/pypi/db/metadata.json'
 * Running g-sorcery... # ( cd /var/lib/layman/pypi  && /usr/bin/g-sorcery gs-pypi -o /var/lib/layman/pypi generate-tree )
 * tree generation
 * no package with name pint found

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/g-sorcery", line 18, in <module>
    sys.exit(g_sorcery.main())
  File "/usr/lib64/python3.4/site-packages/g_sorcery/g_sorcery.py", line 68, in main
    return backend.instance(sys.argv[2:], config, global_config)
  File "/usr/lib64/python3.4/site-packages/g_sorcery/backend.py", line 652, in __call__
    return args.func(args, config, global_config)
  File "/usr/lib64/python3.4/site-packages/g_sorcery/backend.py", line 530, in generate_tree
    dependencies |= self.get_dependencies(pkg_db, pkg)
  File "/usr/lib64/python3.4/site-packages/g_sorcery/backend.py", line 351, in get_dependencies
    raise DependencyError(error)
g_sorcery.exceptions.DependencyError: no package with name pint found
 * Failure result returned from g-sorcery
 * Adding repository "pypi" failed! Possible remains of the operation have NOT been removed and may be left at "/var/lib/layman/pypi". Please remove them manually if required.

 * CLI: Errors occurred processing action add
 * Adding repository "pypi" failed! Possible remains of the operation have NOT been removed and may be left at "/var/lib/layman/pypi". Please remove them manually if required.
```

`pint` does exist: https://pypi.python.org/pypi/Pint

**Comment by sjlongland** [comment]
… and another where pypi and `gs-pypi` disagree: `CoAPthon`.  Problem reproduced with latest `master` branch of `gs-pypi`:

```
 * Running g-sorcery... # ( cd /var/lib/layman/pypi  && /usr/bin/g-sorcery gs-pypi -o /var/lib/layman/pypi generate-tree )
 * tree generation
!!! Repository 'pypi' is missing masters attribute in '/var/lib/layman/pypi/metadata/layout.conf'
!!! Set 'masters = gentoo' in this file for future compatibility
 * no package with name CoAPthon found

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/g-sorcery", line 18, in <module>
    sys.exit(g_sorcery.main())
  File "/usr/lib64/python3.4/site-packages/g_sorcery/g_sorcery.py", line 68, in main
    return backend.instance(sys.argv[2:], config, global_config)
  File "/usr/lib64/python3.4/site-packages/g_sorcery/backend.py", line 652, in __call__
    return args.func(args, config, global_config)
  File "/usr/lib64/python3.4/site-packages/g_sorcery/backend.py", line 530, in generate_tree
    dependencies |= self.get_dependencies(pkg_db, pkg)
  File "/usr/lib64/python3.4/site-packages/g_sorcery/backend.py", line 351, in get_dependencies
    raise DependencyError(error)
g_sorcery.exceptions.DependencyError: no package with name CoAPthon found
 * Failure result returned from g-sorcery
```
